/**
 * S3 buckets for the chatbot backend.
 *
 * 7 buckets grouped by purpose (the two eval buckets exist only when the
 * eval pipeline is enabled, `enableEval`):
 *
 *   Knowledge Base (Bedrock RAG)
 *     - KnowledgeSourceBucket   — Source documents ingested into OpenSearch
 *     - KnowledgeBaseSupplementalBucket — Images extracted by multimodal parsing
 *
 *   Feedback & Evaluation
 *     - FeedbackDownloadBucket  — CSV exports of feedback data for admin download
 *     - EvalResultsBucket       — RAGAS evaluation output files
 *     - EvalTestCasesBucket     — Uploaded test case JSON for eval pipeline
 *
 *   Excel Index (structured contract data)
 *     - ContractIndexBucket     — .xlsx uploads at indexes/{id}/latest.xlsx;
 *                                  S3 event triggers the parser Lambda
 *
 *   Sync
 *     - DataStagingBucket       — Staging area for the weekly sync orchestrator;
 *                                  files land here before being routed to KB or index
 *
 * Design decisions:
 *   - KB and feedback/eval buckets are versioned for auditability.
 *   - ContractIndexBucket and DataStagingBucket are NOT versioned because they
 *     hold transient data replaced on each upload/sync cycle.
 *   - All buckets block public access, enforce SSL, and use RETAIN removal policy.
 *   - CORS is configured per-bucket: KB/feedback/eval allow full CRUD from the
 *     frontend origin; index/staging buckets only need PUT/GET/HEAD.
 *   - Resources are created on `scope` (not `this`) to preserve CloudFormation
 *     logical IDs and avoid accidental bucket recreation on refactors.
 */
import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import { Construct } from "constructs";
import { NagSuppressions } from 'cdk-nag';

export class S3BucketStack extends Construct {
  public readonly knowledgeBucket: s3.Bucket;
  public readonly knowledgeBaseSupplementalBucket: s3.Bucket;
  public readonly feedbackBucket: s3.Bucket;
  public readonly evalResultsBucket?: s3.Bucket;
  public readonly evalTestCasesBucket?: s3.Bucket;
  public readonly contractIndexBucket: s3.Bucket;
  public readonly dataStagingBucket: s3.Bucket;

  constructor(scope: Construct, id: string, allowedOrigin: string, enableEval: boolean) {
    super(scope, id);

    // Resources use `scope` (not `this`) to preserve existing CloudFormation
    // logical IDs. Switching to `this` would change IDs and recreate buckets.

    // ─── Knowledge Base ────────────────────────────────────────────────

    // Source documents for the Bedrock Knowledge Base.
    // Also stores metadata.txt generated by the metadata handler Lambda.
    this.knowledgeBucket = new s3.Bucket(scope, 'KnowledgeSourceBucket', {
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      cors: [{
        allowedMethods: [s3.HttpMethods.GET, s3.HttpMethods.POST, s3.HttpMethods.PUT, s3.HttpMethods.DELETE],
        allowedOrigins: [allowedOrigin],
        allowedHeaders: ['*'],
      }],
    });

    // Supplemental storage required by Bedrock KB when parsingModality=MULTIMODAL.
    // The multimodal parser extracts page images/visual elements while transcribing
    // documents and writes them here; KB reads from this bucket at retrieval time.
    // Not versioned — derived assets that can be regenerated by re-running ingestion.
    // No CORS — only Bedrock service-side reads/writes; never accessed from the browser.
    this.knowledgeBaseSupplementalBucket = new s3.Bucket(scope, 'KnowledgeBaseSupplementalBucket', {
      versioned: false,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
    });

    // ─── Feedback & Evaluation ──────────────────────────────────────────

    // Holds CSV exports of feedback data that admins download from the UI.
    this.feedbackBucket = new s3.Bucket(scope, 'FeedbackDownloadBucket', {
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      cors: [{
        allowedMethods: [s3.HttpMethods.GET, s3.HttpMethods.POST, s3.HttpMethods.PUT, s3.HttpMethods.DELETE],
        allowedOrigins: [allowedOrigin],
        allowedHeaders: ['*'],
      }],
    });

    if (enableEval) {
      // RAGAS evaluation output files (JSON metric results per run).
      this.evalResultsBucket = new s3.Bucket(scope, 'EvalResultsBucket', {
        versioned: true,
        removalPolicy: cdk.RemovalPolicy.RETAIN,
        blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
        enforceSSL: true,
        cors: [{
          allowedMethods: [s3.HttpMethods.GET, s3.HttpMethods.POST, s3.HttpMethods.PUT, s3.HttpMethods.DELETE],
          allowedOrigins: [allowedOrigin],
          allowedHeaders: ['*'],
        }],
      });

      // Uploaded test case JSON files consumed by the evaluation Step Functions pipeline.
      this.evalTestCasesBucket = new s3.Bucket(scope, 'EvalTestCasesBucket', {
        versioned: true,
        removalPolicy: cdk.RemovalPolicy.RETAIN,
        blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
        enforceSSL: true,
        cors: [{
          allowedMethods: [s3.HttpMethods.GET, s3.HttpMethods.POST, s3.HttpMethods.PUT, s3.HttpMethods.DELETE],
          allowedOrigins: [allowedOrigin],
          allowedHeaders: ['*'],
        }],
      });
    }

    // ─── Excel Index ────────────────────────────────────────────────────

    // .xlsx uploads land at indexes/{id}/latest.xlsx. An S3 event triggers
    // the parser Lambda which reads the file and populates DynamoDB.
    // Not versioned — each upload fully replaces the previous index data.
    this.contractIndexBucket = new s3.Bucket(scope, 'ContractIndexBucket', {
      versioned: false,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      cors: [{
        allowedMethods: [s3.HttpMethods.PUT, s3.HttpMethods.GET, s3.HttpMethods.HEAD],
        allowedOrigins: [allowedOrigin],
        allowedHeaders: ['*'],
      }],
    });

    // ─── Sync ──────────────────────────────────────────────────────────

    // Staging area for the weekly sync orchestrator. External data lands here
    // first, then the orchestrator copies files to KB or index buckets as
    // appropriate and cleans up staging. Not versioned — files are transient.
    this.dataStagingBucket = new s3.Bucket(scope, 'DataStagingBucket', {
      versioned: false,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      cors: [{
        allowedMethods: [s3.HttpMethods.PUT, s3.HttpMethods.GET, s3.HttpMethods.HEAD],
        allowedOrigins: [allowedOrigin],
        allowedHeaders: ['*'],
      }],
    });

    // Server access logging is enabled where it pays for itself (the website
    // and CloudFront buckets). These buckets are private, reached only through
    // IAM-scoped Lambdas/Bedrock or presigned URLs, and CloudTrail data events
    // can be enabled per account if object-level auditing is required.
    const unloggedBuckets = [
      this.knowledgeBucket,
      this.knowledgeBaseSupplementalBucket,
      this.feedbackBucket,
      this.evalResultsBucket,
      this.evalTestCasesBucket,
      this.contractIndexBucket,
      this.dataStagingBucket,
    ];
    for (const bucket of unloggedBuckets) {
      if (!bucket) continue;
      NagSuppressions.addResourceSuppressions(bucket, [{
        id: 'AwsSolutions-S1',
        reason: 'Private application bucket accessed only via scoped IAM roles or short-lived presigned URLs; access logging omitted to avoid cost (CloudTrail data events can be enabled per account).',
      }]);
    }
  }
}
